//<li>list item number three</li>\
var terminosycondiciones_latino ="<div id='terms'> \
	<h3>Términos y Condiciones</h3> \
	<h4>I- Glosario de Términos</h4>\
	<ul>\
		<li>Gynopharm Sociedad Anónima, en adelante conocida como la Empresa: es la empresa que ofrece el servicio detallado en el presente documento por medio de una aplicación a los usuarios a los que se les brinda la apertura de una cuenta con su nombre y correo electrónico.</li>\
		<li>CFR PHARMACEUTICALS: es el nombre comercial de la Empresa por medio de la cual la misma opera. Para los efectos del presente documento, Gynopharm S.A. y CFR Pharmaceuticals deberán entenderse como la misma empresa que ofrece el servicio.</li>\
		<li>Usuaria / cliente final: son las personas a las que se les ofrece el servicio de beneficiarse con ofertas en la compra de sus medicamentos y participar en diversas promociones, para apoyarles en el cumplimiento de su tratamiento médico, a través de la aplicación.</li>\
		<li>Aplicación: es el programa informático diseñado por CFR Pharmaceuticals como herramienta para permitir a las usuarias recibir información sobre promociones y participar en sorteos y actividades de la Empresa. La aplicación es descargada en el teléfono inteligente u otro dispositivo móvil por elección de la usuaria, y su descarga podrá ser gratuita u onerosa a elección de CFR Pharmaceuticals.La aplicación podrá ser descargada a través de las tiendas virtuales que CFR Pharmaceuticals elija.</li>\
		<li>Contenido: significa, sin limitación, todos los textos, imágenes, audio, video y gráficos (y todas sus mejoras, suplementos, actualizaciones, revisiones y/o correcciones) provistos por CFR Pharmaceuticals a través de su aplicación.</li>\
		<li>BELLACLICK: es el programa elaborado y ofrecido por CFR Pharmaceuticals y que constituye en un sistema de apoyo en tratamiento médico.</li>\
		<li>CUENTA : Consiste en el nombre completo de la usuaria para el ingreso a la aplicación, y el cual será de uso exclusivo y no podrá ser compartido a terceras personas.</li>\
		<li>Información de registro: consiste en datos personales, los cuales podrán ser entre los siguientes: nombre completo, teléfono, correo electrónico, nombre del médico que le atiende, sin perjuicio de que existan otros. Estos datos deberán ser siempre veraces y actualizados.</li>\
		<li>Puntos de venta/canje: son las cadenas de farmacias o farmacias independientes en las que las usuarias pueden adquirir los medicamentos o tratamientos y canjear productos de acuerdo con las promociones de la aplicación. De conformidad con la invitación abierta publicada en prensa, cualquier farmacia que desee participar en el programa brindado por CFR PHARMACEUTICALS podrá hacerlo, bajo sometimiento a las pautas dictadas por la Empresa.</li>\
		<li>Catálogo o Revista de promociones: consiste en una sección de la aplicación en la que se describen las promociones que ofrece CFR Pharmaceuticals mes a mes, así como información sobre belleza, higiene, cuido personal y demás información relativa al tema de la salud.</li>\
		<li>Factura: documento que emite como punto de venta la farmacia al comprador o usuaria con la indicación precisa y detallada de los productos adquiridos, cantidad de los mismos y su precio, así como de la fecha de la compra y número de factura.</li>\
		<li>Control de toma: consiste en una sección de la aplicación en la que CFR Pharmaceuticals brinda un apoyo a la usuaria al permitirle agendar el nombre del medicamento que debe tomar, la dosis, la periodicidad y demás detalles relacionados, pudiendo preestablecer una alarma en su dispositivo móvil para recordarle a la usuaria a tomar su dosis.</li>\
	</ul>\
	<h4>II- Aceptación</h4>\
	<p>Como usuaria del programa BELLACLICK, (en adelante \"el programa\"), la usuaria acepta respetar y acatar estrictamente los términos y condiciones de esta Política de Uso, que a continuación se enuncian. El hecho de ingresar a la aplicación, crear una cuenta, participar en las promociones de uno o más medicamentos, implicará para la usuaria la aceptación tácita del presente acuerdo o Política de Uso. Por lo anterior será absolutamente necesario que lea cuidadosamente este documento en su totalidad, a efectos de evitar confusiones.</p>\
	<h4>III- Servicio</h4>\
	<p>CFR PHARMACEUTICALS podrá en cualquier momento suspender, en forma temporal o definitiva, la suscripción de aquellos usuarios de los que se compruebe que no han cumplido a cabalidad las condiciones estipuladas en este documento, cuando al registrarse brinden información falsa o inexacta, y en cualquier otro caso, a discreción de la empresa.</p>\
	<p>Todas las promociones son válidas en las cadenas de farmacias o farmacias independientes que han decidido participar como puntos de venta/canje de los medicamentos seleccionados para la aplicación. Previo a la adquisición de cualquier oferta, el paciente debe contar con la debida receta médica para mostrarla en cualquiera de estos puntos, ya que es un requisito indispensable e inexcusable, y en el entendido de que todo medicamento de previo a ser entregado requiere receta médica. La farmacia deberá haber comprobado que exista dicha receta médica para el medicamento del que se trate. Dicha receta médica deberá haber sido otorgada posterior a una consulta con un médico especializado en el área de la salud correspondiente a efectos de tener bajo control los efectos secundarios que todo medicamento posee.</p>\
	<p>El servicio ofrecido a través de la aplicación BELLACLICK es de propiedad exclusiva de esta empresa y constituye un servicio gratuito para los usuarios, por lo que deberán cumplir estrictamente con las condiciones señaladas en este documento. Sin embargo, CFR PHARMACEUTICALS se reserva el derecho de cobrar en el futuro por este servicio así como cobrar por cada descargo de la aplicación.</p>\
	<p>El contenido y los servicios ofrecidos por medio de la aplicación son exclusivamente para uso de la usuaria, y los medicamentos entregados como beneficio de canje/oferta no podrán ser ofrecidos para la venta, ni transferida su propiedad a terceros bajo ninguna circunstancia.</p>\
	<p>CFR PHARMACEUTICALS podrá en cualquier momento suspender, en forma temporal o definitiva, la suscripción de aquellos usuarios de los que se compruebe que no han cumplido a cabalidad las condiciones estipuladas en este documento, cuando al registrarse brinden información falsa o inexacta, y en cualquier otro caso, a discreción de la empresa.</p>\
	<h4>IV- Seguridad de la cuenta</h4>\
	<p>La usuaria  será responsable de  recordar el nombre registrado en forma confidencial. La usuaria  se compromete a notificar inmediatamente a la empresa CFR PHARMACEUTICALS del uso desautorizado, real o sospechado, de su cuenta.</p>\
	<h4>V- Acerca del abastecimiento de medicamentos</h4>\
	<p>CFR PHARMACEUTICALS ofrecerá a las usuarias una serie de medicamentos en los términos que indiquen cada una de las promociones que se publiquen a través de la aplicación. Esta empresa no garantiza que ni ella ni las farmacias que fungen como puntos de venta/canje siempre estén abastecidas de todos los medicamentos solicitados, lo cual depende de la oferta y la demanda de los mismos en el mercado. A pesar de que esta es una empresa farmacéutica, es posible que algunos medicamentos estén agotados a la hora de la solicitud, de lo cual de ser el caso, se le podrá avisar a la usuaria.</p>\
	<h4>VI- Conducta del usuario</h4>\
	<p>Al aceptar este documento, la usuaria conviene utilizar los servicios brindados por la aplicación de la manera acá estipulada, y queda absolutamente prohibida su utilización distinta de la que acá se describe, de manera que de demostrarse un uso incorrecto se podrá proceder con la eliminación de la usuaria y se pondrá fin a los beneficios otorgados por la aplicación, sin necesidad de previo aviso.</p>\
	<h4>VII- Propiedad Intelectual</h4>\
	<p>La aplicación elaborada por CFR Pharmaceuticals y todo el material contenido en la misma tienen reservados todos los Derechos. El usuario no podrá modificar, copiar, reproducir, transmitir, distribuir, publicar, crear obras derivadas, exhibir ni de otro modo transferir o explotar comercialmente ningún material contenido en este sitio, en su totalidad o parcialmente. Está estrictamente prohibida la redistribución, retransmisión o publicación de cualquier material copiado sin el consentimiento expreso y por escrito de CFR Pharmaceuticals. El usuario deberá respetar todos los derechos de autor contenidos dentro de avisos, artículos, notas y/o noticias contenidas en la aplicación. Mediante el descargo de la aplicación y la creación de una cuenta, el usuario se compromete a no infringir los derechos de propiedad intelectual de CFR Pharmaceuticals.</p>\
	<p>CFR PHARMACEUTICALS es una marca registrada. Nada de lo establecido y/o contenido en la aplicación podrá ser interpretado como equivalente al otorgamiento, expreso o implícito, de una licencia o cualquier otro derecho de uso de las marcas exhibidas en la aplicación, sin el expreso consentimiento de CFR Pharmaceuticals. El uso de las marcas exhibidas en la aplicación está estrictamente prohibido, excepto que dicho uso se efectúe conforme lo establecido en esta Política de Uso. CFR Pharmaceuticals hará respetar sus derechos de Propiedad Intelectual con el máximo rigor permitido por la ley, incluyendo el inicio de acciones penales.</p>\
	<h4>VIII- Declaración de descargo de responsabilidad</h4>\
	<p>Al aceptar este documento, la usuaria consiente inexcusablemente que libra a CFR Pharmaceuticals de cualquier responsabilidad por el uso de medicamentos que se incluyan en la aplicación y/o promocionados a través de la aplicación o punto de venta. Al adquirir un medicamento en específico, la usuaria deberá estar completamente seguro y garantiza que existe una receta médica que respalde dicho pedido, la cual podrá ser solicitada por CFR Pharmaceuticals o por el punto de venta/canje. La Empresa no se hará responsable por cualquier efecto no deseado después del consumo o aplicación del medicamento, ya que se entiende que existe una consulta previa ante un médico especializado, el cual habrá entregado la respectiva receta médica y habrá hecho las observaciones y advertencias necesarias.</p>\
	<p>Sobre la sección de la aplicación conocida como Control de Toma, en que la aplicación permite al usuario agendar el nombre del medicamento que consume, la dosis y periodicidad del mismo, y la fecha en que inicia a ingerirlo, la usuaria hace constar que a pesar de esta herramienta, es exclusivamente su responsabilidad recordar la toma o aplicación del medicamento o tratamiento médico. CFR PHARMACEUTICALS no se hace responsable por el olvido de la ingesta o aplicación del producto, y es exclusiva responsabilidad del cliente completar su tratamiento médico y tomarlo de acuerdo a la dosis sugerida por su médico.</p>\
	<h4>IX- Cambios en el servicio o en la Política de Uso</h4>\
	<p>CFR Pharmaceuticals se reserva el derecho de modificar, suspender o discontinuar el servicio brindado a través de la aplicación en cualquier momento, sin necesidad de que medie previo aviso a los usuarios. Además, la empresa se reserva el derecho de modificar esta Política de Uso en cualquier momento, de modo que, periódicamente, el usuario tendrá la oportunidad de informarse sobre los cambios producidos.</p>\
	<h4>X- Incumplimiento de acatar la Política de Uso</h4>\
	<p>La usuaria acepta y reconoce que como consecuencia del incumplimiento de esta Política de Uso o de cualquiera de los otros avisos legales contenidos en la aplicación, CFR Pharmaceuticals podrá suspender o dar por concluida su calidad de usuaria sin que medie previo aviso.</p>\
	<h4>XI- Ley aplicable y jurisdicción competente</h4>\
	<p>Esta Política de Uso será interpretada de conformidad con las leyes del país en que el usuario se encuentre domiciliado. Cualquier controversia que surja en relación con lo establecido en esta Política de Uso, será resuelta definitivamente por los Tribunales o institución competente del país en que el usuario se encuentre domiciliado, a cuya jurisdicción los usuarios se someten.</p>\
	<h4>XII- Confirmación de acuerdo</h4>\
	<p>Esta Política de Uso constituye el acuerdo total entre el usuario y CFR Pharmaceuticals.</p>\
</div>";